[package]
name = "emitbrown"
version = "0.1.0"
authors = ["Cheng JIANG <cheng.jiang@outlook.fr>"]
edition = "2018"
description = "event emitter based on google swisstable"

[dependencies]
hashbrown = "0.1"
