[package]
name = "emitbrown"
version = "0.1.5"
authors = ["Cheng JIANG <cheng.jiang@outlook.fr>"]
edition = "2018"
description = "event emitter based on google swisstable"
license = "MIT"

[dependencies]
hashbrown = "0.6.3"
